### ISSUE TITLE
A question about licensing

### ISSUE THREAD

**Issue by lokesh-krishna** [Zoldyako/Zoldyako-Krita-Themes#3]
Hey, 
Just discovered your themes today and love how simple they are and how well that lends itself to modification. However I noticed that your repo doesn't have a license and wanted to confirm if this was intentional. 

When a project doesn't have a license then it typically means that users do not have permission to use, modify or share the project. That however doesn't seem to be what you want so could you please add an appropriate license?

**Comment by Zoldyako** [comment]
Hello! First I'm happy you liked my themes for Krita! As you have asked, I added the license (MIT) to the repo.
